Adding CONTRIBUTING.md and updated the content
joestrong/retroachievements-composer pull request #8
Opened 2017-10-12 23:02 UTC by Supun94

PR for issue #7

2017-10-12 23:26 UTC, joestrong requested changes
Really nice, thanks! Just a couple of amends please.

Also, can you change this to branch off the latest version of the develop branch (like the new contributing guide says 😄 )

2017-10-12 23:26 UTC, joestrong commented on CONTRIBUTING.md
> +RetroAchievements.org is a volunteer effort. We encourage you to pitch in and [join the team](https://github.com/joestrong/retroachievements-composer/graphs/contributors)!
This is not for the RetroAchievements.org site itself, so can you change 'RetroAchievements.org' for 'This project'

2017-10-12 23:26 UTC, joestrong commented on CONTRIBUTING.md
> +RetroAchievements.org Team
Can you remove this line (I'm not part of the retro achievements site itself)

2017-10-12 23:26 UTC, joestrong commented on CONTRIBUTING.md
> +CONTRIBUTING file inspired/based on [rails contrubiting](https://github.com/rails/rails/blob/master/CONTRIBUTING.md)
Can you remove this line?

2017-10-14 03:34 UTC, Supun94 commented
@joestrong I have done the changes as you mentioned. Please review :) . Do you need this PR for [develop branch](https://github.com/joestrong/retroachievements-composer/tree/develop) ? (Sorry I didn't what you mentioned in the comment)

2017-10-14 11:56 UTC, joestrong commented
Yeah, all PRs need to be a branch from develop, with the intent to merge into develop.

Can you rebase your commits onto a branch, branching off the tip of the latest develop branch? And rename the branch to something more fitting to the changes

2017-10-14 12:19 UTC, Supun94 commented
@joestrong Please find this #11 PR and review.

2017-10-15 12:30 UTC, closed without merging